# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef26191e835c474d8c491cdd9644b543ca7a88eb1568a8cddb17b95d6fe9194270fabd43492f31f8e1a3135b885874aa383fbcd56dacc1b75ab0900833904b7e

test:
  secret_key_base: 8ed8561ecd48147ad2f24df33f97aa52a913bb655de552b441b82934a92e6012b6264cd8bfb24c2905033805171b41bd04b41ebdad6037c6a9afb2515d0a48d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
